version: '3'
services:
  proxy:
    build: ./
    networks:
    - site1
    - site2
    ports:
    - '80:80'
    - '443:443'
# kết nối đến network của ex1_default và ex2_default
networks:
  site1:
    external:
      name: ex1_default
  site2:
    external:
      name: ex2_default